global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Configuración de proveedor de archivos para certificados estáticos
providers:
  file:
    filename: /etc/traefik/traefik.yaml
    watch: true
  
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy_net

# Certificados TLS estáticos - ESTA ES LA CLAVE
tls:
  certificates:
    - certFile: "/certs/web-nginx01.local+2.pem"
      keyFile: "/certs/web-nginx01.local+2-key.pem"
  
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/web-nginx01.local+2.pem"
        keyFile: "/certs/web-nginx01.local+2-key.pem"